
#EMEFANA Service
FROM iamiddy/jdk8
MAINTAINER <iddyiam@gmail.com> Iddy Magohe

ADD emefana_service /opt/emefana_service

EXPOSE 8080

WORKDIR /opt/emefana_service
CMD ["java", "-jar", "e-mefana.jar"]

